[general]
import = ["~/.config/alacritty/themes/tokyo_night.toml"]

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 5, y = 5 }
opacity = 0.925

[font]
size = 16.0
normal = { family = "SF Mono", style = "Regular"}
bold = { family = "SF Mono", style = "Bold"}
italic = { family = "SF Mono", style = "Italic"}

[scrolling]
history =     10000

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 1000
