let mapleader = " "
set nocompatible
filetype plugin indent on
set encoding=utf-8
set syntax=on

set number
set relativenumber
set cursorline
set wrap
set scrolloff=8
set wildmenu
set showcmd

set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
set autoindent
set smartindent

set hlsearch
set incsearch
set ignorecase
set smartcase

set backspace=indent,eol,start
set hidden
set nobackup
set noswapfile
set undofile

inoremap jk <Esc>
inoremap jj <Esc>
